### PR TITLE
Prevent AudioContext creation on constructor

### PR DESCRIPTION
**Pull request by rotem925**
Moved AudioContext to be attached to the prototype, so that AudioContext created only once.
This will prevent the error that comes from chrome for example:

Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6)

### CODE REVIEW

**Comment by rotem925** [comment]
@chris-rudmin 
Can you help me understand why this test fails?

**Comment by rotem925** [comment]
@chris-rudmin ,
that's I guess because I've pushed the min file.
I've reverted it, I guess that would be generated..

**Comment by chris-rudmin** [comment]
Thanks for the improvement! Could you add unit tests for this change? Something like instantiate two instances and validate that the audioContexts are shared?

**Comment by chris-rudmin** [comment]
I'm doing some changes so I will add a test for this. Thanks!

**Comment by rotem925** [comment]
@chris-rudmin 
Ok,
Thank you!

**Pull request merged**
